### ISSUE TITLE
PHP Site class BaseUrl method putting trailing slash at end of url if Public is document Root

### ISSUE THREAD

**Issue by lablnet** [alphazframework/framework#153]
https://github.com/zestframework/Zest_Framework/blob/master/src/Site/Site.php#L57

Live Demo (when Public is document root)
https://zestframework.xyz/index.php?zestinfo

If Public is not doc root then 
![screenshot 94](https://user-images.githubusercontent.com/27757785/53705658-e3629680-3e47-11e9-9a1e-c6acdaec7eda.png)

**Comment by peter279k** [comment]
Actually, this is about the exposed system information.

We should add the basic authentication to make sure that this information page is only available for admin users.

**Comment by lablnet** [comment]
@peter279k  sorry, i delete your comment because you was misunderstand 

The problem here with that if Public folder is not document root then this method ok but if public folder is document root it append extra slash at end of URL

**Comment by lablnet** [comment]
#163

**Comment by lablnet** [comment]
@peter279k  Patch had applied to Zest framework website 
this issue has been resolved 
https://zestframework.xyz/zestinfo
