### ISSUE TITLE
Coding style check

### ISSUE THREAD

**Issue by peter279k** [alphazframework/framework#156]
As title, I notice that the coding style is not united on this project.

We can find that they have the camel-case and underline-based variable declaration.

Do you consider the PSR-2 coding style?

**Comment by lablnet** [comment]
The style being used something like

## Classes
Classes name first letter is uppercase
```php 
class Logger {}
```
if class name has more then one word then 
```php
class AliesLoader {}
```
## Methods
Methods are camel case like
```php
public isLogin() {}
```
or
```php
public getUserById() {}
```

## functions
mostly functions name with underscore like
```php
function is_login() {}
```

so i think those above follow psr-2 standard

about control structures and iteration thats also according to psr standard 

yes you are right the variable name is not according to psr-2 standard

**Comment by peter279k** [comment]
How about the variable declaration on methods?

**Comment by lablnet** [comment]
@peter279k  yes need to fix this in codes

**Comment by lablnet** [comment]
As we followed the PSR-2 Standard so this issue is closing now...
