### ISSUE TITLE
Response send method not working as it should be

### ISSUE THREAD

**Issue by lablnet** [alphazframework/framework#168]
Everything working fine but the body is not print out

https://github.com/zestframework/Zest_Framework/blob/master/src/http/Headers.php#L194

that was the same problem with our [website](https://zestframework.xyz/)

So in this case the view not working

https://github.com/zestframework/Zest_Framework/blob/master/src/View/View.php#L119

i revert this view to this, then the web works fine you can see above Zest framework link.
```php
public static function view($file, array $args = [], bool $minify = false, array $headers = [], $code = 200)
    {
        $headers['Content-Type'] = 'text/html';
        if ($minify === true) {
            $minify = new Minify();
            self::randerTemplate($file, $args);
            /*$config = [
                'code'    => $code,
                'body'    => $minify->htmlMinify(ob_get_clean(), 'code'),
                'headers' => [
                    $headers,
                ],
            ];
            $response = new Response($config);
            //$response->send();
              echo $response->send()*/
            echo $minify->htmlMinify(ob_get_clean(), 'code');
        } else {
            self::randerTemplate($file, $args);
            /*$config = [
                'code'    => $code,
                'body'    => ob_get_clean(),
                'headers' => [
                    $headers,
                ],
            ];
            $response = new Response($config);
            //$response->send();
              echo $response->send()*/
            echo ob_get_clean();
        }
    }
#reference https://github.com/zestframework/Zest_Framework/blob/master/src/View/View.php#L105
```

**Comment by lablnet** [comment]
@peter279k  or @Maikuolan  looking for your help

**Comment by peter279k** [comment]
It seems that the `Response` class should be the problem.

Consider the following `Headers::send` method:

```php
    public function send($code = null, array $headers = null)
    {
        if ($code !== null) {
            $this->withStatus($code);
        }
        if ($headers !== null) {
            $this->setHeaders($headers);
        }
        $body = $this->body;
        if (array_key_exists('Content-Encoding', $this->headers)) {
            $body = self::encodeBody($body, $this->headers['Content-Encoding']);
            $this->headers['Content-Length'] = strlen($body);
        }
        $this->sendHeaders();
        echo $body;
    }
```

I think the `Content-Encoding` header check should be the issue and I think it can remove them and try this code again.

**Comment by lablnet** [comment]
Yes, you were right

following patch applied to  http://beta.zestframework.xyz/

```php
    public function send($code = null, array $headers = null)
    {
        if ($code !== null) {
            $this->withStatus($code);
        }
        if ($headers !== null) {
            $this->setHeaders($headers);
        }

        $body = $this->body;

        if (array_key_exists('accept-encoding', $this->headers)) {
            $body = static::encodeBody($body, $this->headers['accept-encoding']);
        }
        $this->headers['Content-Length'] = strlen($body);
        $this->sendHeaders();
        echo static::decodeBody($body, $this->headers['accept-encoding']);
    }

```

previous it was returning false 
```php
if (array_key_exists('Content-Encoding', $this->headers)) {}
```
As i see the header `Content-Length` is required
Also there is no header exists ```Content-Encoding``` 
So we can encode, and decode body by ```accept-encoding``` header is this right approach?

**Comment by peter279k** [comment]
The we browser uses the `Accept-Encoding` on request header to tell server it can aceept which content encoding approach.

**Comment by peter279k** [comment]
The `Content-Type` and `Content-Length` are required on response header.

And the `Content-Encoding` is optional header.

I think using the following approach to achieve the `Content-Encoding` condition:

- Read the request header.
- If the `Accept-Encoding` is existed, find the accepted `encoding` appraoch on request header.
And set the current/correct `Content-Encoding` header on response header.
- Send the response header.

**Comment by lablnet** [comment]
Thanks

like here we are checking (point 1,2)
```php
if (array_key_exists('accept-encoding', $this->headers)) {
```
then we have to do like

```php
//static::encodeBody($body, $this->headers['accept-encoding']); need to replace this
$this->headers['Content-Encoding']  = $this->headers['accept-encoding'];
```
also need to replace this

```php
echo static::decodeBody($body, $this->headers['accept-encoding']);
```
with just
```php
echo $body;
```
Is that right what are are proposing?

**Comment by lablnet** [comment]
I see to set 
```php
$this->headers['Content-Encoding']  = $this->headers['accept-encoding'];
```
is not working at all

**Comment by peter279k** [comment]
The `Accept-Encoding` will be single or multiple definition on request header.

And `Content-Encoding` on the response header is similar with `Accept-Encoding`.

Please look at the [Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) and [Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) to know more details.

**Comment by peter279k** [comment]
The syntaxes are different. Please look at following blocks:

```
Content-Encoding: gzip
Content-Encoding: compress
Content-Encoding: deflate
Content-Encoding: identity
Content-Encoding: br

// Multiple, in the order in which they were applied
Content-Encoding: gzip, identity
Content-Encoding: deflate, gzip
```

```
Accept-Encoding: gzip
Accept-Encoding: compress
Accept-Encoding: deflate
Accept-Encoding: br
Accept-Encoding: identity
Accept-Encoding: *

// Multiple algorithms, weighted with the quality value syntax:
Accept-Encoding: deflate, gzip;q=1.0, *;q=0.5
```

And you cannot assign the `Accept-Encoding` to `Content-Encoding` directly.

You should parse the header name and value firstly.

**Comment by lablnet** [comment]
yes but in such case it also not work

```php
 $this->headers['Content-Encoding']  = 'gzip, deflate';
```

so th parse header to extract this is useless

**Comment by lablnet** [comment]
According to DOCS, accept encoding is request header, but wht in this case response header?

![Screenshot (134)](https://user-images.githubusercontent.com/27757785/54098450-7bc3c280-43d6-11e9-8b7d-363b93ead661.png)

**Comment by peter279k** [comment]
If you want to use the `Content-Encoding`, you should notice these two points:

- The `Content-Encoding` module is defined/enabled on Apache config correctly.
- You use the PHP code (like `gzencode` function) when sending response contents on specific encoded header.

Here are the useful links:

- https://www.garron.me/en/linux/enable-gzip-mod_deflate-compression-apache.html
- https://gist.github.com/ryoakg/68d750c3787e046d5c50a4c07ae66acc

**Comment by lablnet** [comment]
@peter279k  Thanks for your reply

You're right 

But still have one problem when we use view within view like
**Home Controller**
```php
<?php

namespace App\Controllers;

class Home extends \Zest\Controller\Controller
{
    public function index()
    {
        view("Home/index");
    }   
}
```
**Home view**
```html
<!DOCTYPE html>
<html>
<head>
	<title>Title</title>
</head>
<body>
	<?=view('Home/nav')?>
	<!--  Rest of code-->
</body>
</html>
```
In view you may see ```<?=view('Home/nav')?>``` we are including another view so in this case the output is stranger
see here http://beta.zestframework.xyz/
the header and footer part is stranger because used within view
but this part work fine where no view included in another view 
http://beta.zestframework.xyz/zestinfo

So how we fix this problem?

**Comment by Maikuolan** [comment]
When looking at the above link, I spotted a typo (the typo is not related to this issue). PR sent.

**Comment by peter279k** [comment]
The problem is about the `View::view` method.

I think you should use [gzdecode ](http://php.net/manual/en/function.gzdecode.php)to decode the compressed content before rendering the view template.

**Comment by peter279k** [comment]
I use the `cURL` command to request get the following response header:

![image](https://user-images.githubusercontent.com/9021747/54141714-28e31d00-4461-11e9-9c87-623aa00f35f9.png)

The `Vary: Accept-Encoding` is existed and it means that this response content is compressed.

**Comment by peter279k** [comment]
And you should know about the HTTP request/response.

* Web browser send request header.
* Zest framework parses request header.
* Zest framework render the compressed content with `View::view` method.
* Zest framework collect and send response headers.

**Comment by lablnet** [comment]
Yes thanks,

working proposal 
```php
    public function send($code = null, array $headers = null)
    {
        if ($code !== null) {
            $this->withStatus($code);
        }
        if ($headers !== null) {
            $this->setHeaders($headers);
        }

        $body = $this->body;
        $this->headers['Content-Length'] = strlen($body);
        $encoding = '';
        if (preg_match('/ *gzip *,?/', $this->headers['accept-encoding']))
           $encoding = 'gzip';
        elseif(preg_match('/ *deflate *,?/', $this->headers['accept-encoding']))
            $encoding = 'deflate';

        //(!empty($encoding)) ? $this->headers['Content-Encoding']  = $encoding : null;
        $body = static::encodeBody($body, $encoding);
        $this->sendHeaders();
        echo static::decodeBody($body, $encoding);
    }
```

But this line 
``` //(!empty($encoding)) ? $this->headers['Content-Encoding']  = $encoding : null;```
still make the problem
