### ISSUE TITLE
Need improvement in Configuration class and function 

### ISSUE THREAD

**Issue by lablnet** [alphazframework/framework#185]
I think we need to improve the configuration class and their respective functions

like now in Zest it something following

```php
$language = __config()->config->language
//Or
$language = config()->config->language

```
This is looking odd it should be something like
```php
$language = __config('app.language');
//Or
$language = config('app.language');
```

And the function prototype something like this
```php
function config ($key = null, $default = null)
{

}
```

SO we can provide default value to avoid requiring Zest for tests as well

What do you think @peter279k @Maikuolan

**Comment by peter279k** [comment]
It seems that you want to create a dot array style for the configuration array.

It's very similar with the config on Laravel framework.

I think it's fine to scratch their approaches to implement our own config `dot` array style.

**Comment by Maikuolan** [comment]
Sorry for not replying earlier. Caught up with other things a little the past few days.

For better understanding: Is this just a question about code style and aesthetics, or about a specific problem (e.g., something not working properly, possible performance improvements, etc)?

**Comment by peter279k** [comment]
@Maikuolan, thank you for your concern, this is about improving configuration array manipulation.

The issue author, @Lablnet wants to replace the object style with the `dot` array style.

Do you have any idea/suggestion on that?

**Comment by Maikuolan** [comment]
Could consider implementing [adbario/php-dot-notation](https://github.com/adbario/php-dot-notation), maybe. I haven't used the library before, but it seems to be able to achieve the desired effect.

**Comment by peter279k** [comment]
I think it can also consider following code about setting config value with dot array style.

```php
function set_value(&$array, $key, $value)
{
    if (is_null($key)) {
        return $array = $value;
    }

    $keys = explode('.', $key);

    while (count($keys) > 1) {
        $key = array_shift($keys);

        if ( ! isset($array[$key]) || ! is_array($array[$key])) {
            $array[$key] = [];
        }

        $array = &$array[$key];
    }

    $array[array_shift($keys)] = $value;

    return $array;
}

```

Here is the sample code:

```php

$array1 = [
    "member1" => "lablet",
    "member2" => "Maikuolan",
];

set_value($array1, 'member3.name', 'peter279k', '.');

var_dump($array1);
```

It will output:
```
array(3) {
  'member1' =>
  string(6) "lablet"
  'member2' =>
  string(9) "Maikuolan"
  'member3' =>
  array(1) {
    'name' =>
    string(9) "peter279k"
  }
}

```

I consider the `Arr` class on `illuminate/support` package, and I hope this will be hopeful for improving the config array manipulation with dot array approach :).

**Comment by lablnet** [comment]
@Maikuolan  Our problem is to reinvent the wheel, that the goal of `Zest` without external dependencies expect core, autoloader and unit testing to make the framework lightweight like `codeigniter`

**Comment by lablnet** [comment]
Let consider this code

After some strug;e i able to invent wheel 

```php
    function set(&$array, $key = null, $value = null, $opr = null)
    {
        if (null === $value) {
            return $array;
        }
        if (null === $key) {
            return $array = $value;
        }
        if (null === $opr) {
            return $array[$key] = $value;
        }

        $keys = explode($opr, $key);
        foreach ($keys as $ks => $key) {
            if (!isset($array[$key])) {
                $array = &$array[$key];
            }
        }
        $array = $value;
        return $array;        
    }
```
Usage
```php

$array1 = [
    "member1" => [
        'name' =>  "lablet"
    ],
    "member2" => [
        'name' => 'Maikuolan'
    ],
];
set($array1, 'member3.name', 'peter279k','.');
var_dump($array1);
```

result prefect as expected

```
array(3) { ["member1"]=> array(1) { ["name"]=> string(6) "lablet" } ["member2"]=> array(1) { ["name"]=> string(9) "Maikuolan" } ["member3"]=> array(1) { ["name"]=> string(9) "peter279k" } }
```

**Comment by peter279k** [comment]
Does this issue accomplish?

**Comment by lablnet** [comment]
Yes it completed, as the Config class completed just waiting of container class then i will merge that PR
