### ISSUE TITLE
Fix Travis CI build

### ISSUE THREAD

**Issue by peter279k** [alphazframework/framework#191]
As title, the Travis CI build is failed due to the configuration file path.

Here is the [Travis CI build log](https://travis-ci.org/zestframework/Zest_Framework).

It's also related issue #185 and I think we can consider following approach to solve this:

- Create the `mock_config.php` file for do unit test in Travis CI build.

I think we can download the `config` file to the specify file path via `wget` command and this work can be defined in `.travis.yml` file.

**Comment by lablnet** [comment]
Yes this work for know
But i am thinking about something like describe in https://github.com/zestframework/Zest_Framework/issues/185

So we can load configs file if exists and in our get `method` there will be option default value
so at core level we can pass default value, is this good approach what do you think?

i am curious How laravel manage their config and passsed tests?

**Comment by peter279k** [comment]
In Laravel framework, it defines/initialize config in tests to do unit test for `Config` class.

You can consider the following code snippet in link:

[Config test](https://github.com/laravel/framework/blob/5.8/tests/Config/RepositoryTest.php)

**Comment by lablnet** [comment]
I see, you're right 

the approach `Mock config` is right here

and you can do this by Sending `PR`

i am not sure but i think we can determine is code running from php unit testing
in `Config` class you can specify that condition to load config from mock file

**Comment by peter279k** [comment]
@Lablnet. After tracing Laravel framework deeply, the `Hashing` work in `laravel/framework` doesn't load any config array.

I think you should separate the ArgonHasher to different the Hashers with different Argon2 algorithm.

You should look at the hashing implementation in [Laravel framework](https://github.com/laravel/framework/tree/5.8/src/Illuminate/Hashing).

We should avoid loading the config because it's not related to the core framework.

The config will only effect on web application and it's `zest/zest`.

The Laravel framework uses the `HashManager` and `HashServiceProvider` classes to load the hash algorithm driver name from config. and these classes are for `laravel/laravel`.

Perhaps we can scratch this approach. My approach is as follows:

- Separate the config loading work from related core `Hashing` classes.
- Using the `HashManager` or `HashServiceProvider` to load config work and dispatch the current Hashing class.
It's fine to ignore these classes in unit tests because they're the `Dispatcher`.
- We only work is to do unit tests for these core `Hashing` classes.

What do you think about that?

**Comment by lablnet** [comment]
Yes you are absolutely right could you create a PR?
