### ISSUE TITLE
Archive component

### ISSUE THREAD

**Issue by peter279k** [alphazframework/framework#220]
**Is your feature request related to a problem? Please describe.**

According to the `Zest_Framework/src/Zip/`, it looks like the Archive only supports the `Zip`.

But it has other archive approaches. For example, the `bzip`, `gzip` and so on.

**Describe the solution you'd like**

Consider creating missed archive components.

Or try considering creating a `Archive` component to support all available archives in this framework.

**Comment by lablnet** [comment]
Yeah that's awesome thanks for grate idea, i haven't think before.
Here is i think approach
the main `Archive` class
and adapters like 'zip', bzip', 'gzip' and others etc
what do you think?

**Comment by peter279k** [comment]
Hi @Lablnet, I can agree that.
