### ISSUE TITLE
Permission denied after installing Zest framework

### ISSUE THREAD

**Issue by lablnet** [alphazframework/framework#236]
Premission dined because whenever user first run zest framework it created default directories 

**here is order**

```
 ../Storage
/Storage/Data
/Storage/Logs
/Storage/Session
/Storage/Cache
/Storage/Backup
```

_In the file_ 

> https://github.com/zestframework/Zest_Framework/blob/master/src/Files/Files.php#L78

**Consider the following method/function:**
```php
    public function systemDirs()
    {
        $this->mkDir('../Storage');
        $this->mkDir('../Storage/Data');
        $this->mkDir('../Storage/Logs');
        $this->mkDir('../Storage/Session');
        $this->mkDir('../Storage/Backup');
        $this->mkDIr('../Storage/Cache');
    }
```

**I change it to following:**
```php
    public function systemDirs()
    {
        $this->permission(route()->root, 0775);
        $this->mkDir(route()->root.'Storage', null, 0775);
        $this->mkDir(route()->root.'Storage/Data', null, 0775);
        $this->mkDir(route()->root.'Storage/Logs', null, 0775);
        $this->mkDir(route()->root.'Storage/Session', null, 0775);
        $this->mkDir(route()->root.'Storage/Backup', null, 0775);
        $this->mkDIr(route()->root.'Storage/Cache', null, 0775);
    }
```

But its not working at all

_**### This issue only occurs when we use Linux based operating system or Macintosh**_

**_Here is snapshort_**

![Screenshot from 2019-07-28 00-34-06](https://user-images.githubusercontent.com/27757785/62002303-6cb48700-b0cf-11e9-9117-77ac6e9e6ea1.png)

**Comment by peter279k** [comment]
The `permission denied` message is presented when using the `mkdir` function.

That's current reason is about the user permission on Unix-like operating system.

It seems that the `www-data` user cannot access `root` privilege user directory.

To solve this problem, I think we have to consider this approach.

The steps are as follows:

- Catch the exception if the `mkdir` function is triggered.
- Check the current owner of directory and PHP execution user.
- Present the clear `permission denied` message and stop the framework build.

When developers get this message, they need to solve the permission by themselves.

If we use the `Docker` container support, we can solve this issue and add commands in `Dockerfile`.

And developers don't need to solve them manually :).

**Comment by lablnet** [comment]
oh so it mean it can not be solved by php directly right?

Am not familar with unix like system remission problem

**Comment by peter279k** [comment]
Hi @Lablnet, thanks for your reply.

It's possible to solve this problem, but it cannot solve this issue with PHP directly.

My suggestion that is mentioned on my previous comment thread and we can consider providing the `Docker` container to build the framework environment.

And it's easy for developers to build their own Zest framework via Docker container.

**Comment by lablnet** [comment]
Yeah

https://github.com/zestframework/Zest_Framework/issues/146

**Comment by lablnet** [comment]
So i think this issue should be close right?

**Comment by peter279k** [comment]
That's right :).
