### ISSUE TITLE
Enchantment of str class

### ISSUE THREAD

**Issue by lablnet** [alphazframework/framework#247]
As title, enchantment of str Class

Need encoding support.

May need more methods like 
1. hasUpperCase
2. hasLowerCase
3. ConvertCase
4. etc...

**Comment by ghost** [comment]
hey, 
do you have any coding guidelines? 
And do you have any other special wishes what kind of methods you need or should I just add everything that comes into my mind?

**Comment by lablnet** [comment]
> hey,
> do you have any coding guidelines?
> And do you have any other special wishes what kind of methods you need or should I just add everything that comes into my mind?


Yes have coding guide
1.You never allow add third-party Composer dependencies or classes
2.You allow to improve existing features or add new features
3. You allow update Zest framework code or core code
4. When you want send pull request. You have provide brief description about code either you update exsting code or adding new feature.
In short every change you made should be standalone.

You may add everything that is in your mind
You may also consider this

hasUpperCase
hasLowerCase
ConvertCase

Thanks you for being interest in Contribution of Zest Framework

**Comment by peter279k** [comment]
@Lablnet, we also consider adding the unit tests for `Str` class.

And it can be reliable for `Str` class method behaviors.

**Comment by lablnet** [comment]
> @Lablnet, we also consider adding the unit tests for `Str` class.
> 
> And it can be reliable for `Str` class method behaviors.

Yeah, it already been their

look

https://github.com/zestframework/Zest_Framework/blob/master/Tests/Data/StrTest.php
