### ISSUE TITLE
SodiumException: key size should be SODIUM_CRYPTO_SECRETBOX_KEYBYTES bytes

### ISSUE THREAD

**Issue by peter279k** [alphazframework/framework#273]
**Describe the bug**
As title.

**Requirements**
1. Zest Framework Version: `3.0`.
2. PHP Version: `7.3.9`.
3. Apache version: `N/A`.
4. PlatForm version and name: `Travis CI build environment`.
5. ErrorLog. The failed Travis CI build log is available [here](https://travis-ci.org/zestframework/Zest_Framework/jobs/592367083).

**Additional context**
The failed error message is as follows during Travis CI build:

```
1) Framework\Tests\EncryptionTest::testSodiumEncrypt
SodiumException: key size should be SODIUM_CRYPTO_SECRETBOX_KEYBYTES bytes
/home/travis/build/zestframework/Zest_Framework/src/Encryption/Adapter/SodiumEncryption.php:84
/home/travis/build/zestframework/Zest_Framework/Tests/Encryption/EncryptionTest.php:26
```

It seems that the we should use the `SODIUM_CRYPTO_SECRETBOX_KEYBYTES` const to generate the cipher text and nonce.

The problematic code is on this [line](https://github.com/zestframework/Zest_Framework/blob/master/src/Encryption/Adapter/SodiumEncryption.php#L83).

**Comment by 2mt-heuser** [comment]
Is this still an issue? I can't seem to reproduce it locally with php7.3.9 + sodium 2.0.22.
All tests work.

**Comment by peter279k** [comment]
I'm not sure that the test is failed during Travis CI build.

Maybe I will try reproducing issue and create related PR on that.

**Comment by peter279k** [comment]
After looking at these codes, this issue has been resolved on latest commit.

Closed.
