### ISSUE TITLE
Wrong Behaviours of Str \hasUpperCase and \hasLowerCase

### ISSUE THREAD

**Issue by lablnet** [alphazframework/framework#274]
Consider the following string

`#-<ae|9_+0a*a!Q?@(z,3R>.BAb)^%R&*+~RG:$`

### Upper Case `Regx`

![image](https://user-images.githubusercontent.com/27757785/66021094-df444780-e502-11e9-9066-30f88837fc8e.png)

same regx use in LowerCase

**Comment by peter279k** [comment]
I'm curious about the `hasLowercase` and `hashUppercase` method implementations.

Should we consider only about the English string lowercase/uppercase conversion?

If possible, we can change into following regular expression:

`hasUppercase`:

```
/([A-Z])/
```

`hasLowercase`:

```
/([a-z])/
```

![image](https://user-images.githubusercontent.com/9021747/66023105-baf86300-e522-11e9-976e-f390cc2f667a.png)

**Comment by lablnet** [comment]
> I'm curious about the `hasLowercase` and `hashUppercase` method implementations.
> 
> Should we consider only about the English string lowercase/uppercase conversion?
> 
> If possible, we can change into following regular expression:
> 
> `hasUppercase`:
> 
> ```
> /([A-Z])/
> ```
> 
> `hasLowercase`:
> 
> ```
> /([a-z])/
> ```
> 
> ![image](https://user-images.githubusercontent.com/9021747/66023105-baf86300-e522-11e9-976e-f390cc2f667a.png)

We need to keep in mind encoding as well, in that case UniCode
