### ISSUE TITLE
Cloudcov key is in the travis config

### ISSUE THREAD

**Issue by ReeceM** [alphazframework/framework#282]
**Describe the bug**
The Travis CI config file contains the `CODECOV_TOKEN`, this goes against standards to keep tokens in the runtime config of the service dashboard and not commit this data to git or revision control.

The way to fix this is to remove the config details and add it as an environment variable under Travis Ci: 

Projects > Zest Framework Repo >  Settings > Environment Variables.

Add the token there and it will still work.

**Requirements**
Applies to the repo, not the running of main framework

**Comment by lablnet** [comment]
![image](https://user-images.githubusercontent.com/27757785/66093518-f5591300-e5a9-11e9-899d-961aa94d5ef6.png)


There is no such option

**Comment by ReeceM** [comment]
Hi @Lablnet, that setting is meant to be set in from the travis-ci section.

If you follow the following link https://travis-ci.org/zestframework/Zest_Framework/settings

You should be logged in and also be able to see the settings tab selected. That should be where you are able to change that.

The below is a screenshot of one of my repos, you should see the similar page:

<img width="949" alt="Screen Shot 2019-10-03 at 07 11 58" src="https://user-images.githubusercontent.com/2767904/66100913-225af500-e5ad-11e9-9d0d-283d54af6550.png">

**Comment by peter279k** [comment]
That's right. Token should not be exposed on `Travis` setting.

It should be a encrypted environment variables.

**Comment by lablnet** [comment]
@ReeceM  Thanks you so much for your time
