### ISSUE TITLE
Tests are failing on Scrutinizer

### ISSUE THREAD

**Issue by lablnet** [alphazframework/framework#335]
As title, tests are failing in `Scrutinizer` to be honest i do not know because tests are passing in my local and in github actions, may be the `php` `zip` extension is not installed but there is no such option in `Scrutinizer`

@peter279k  do you have any idea?

**Comment by peter279k** [comment]
Since GitHub Action has been enabled on this repository, I think it's not very necessary to enable the Scrutinizer and run its CI building work.

**Comment by lablnet** [comment]
Agreed, I've disabled the unit tests on Scrutinizer.
This issue is resolved.
